name: Lint
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: Mambaforge }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: pylint
        shell: bash -l {0}
        run: |
          pylint ec_tools
      - name: black
        shell: bash -l {0}
        run: |
          black --check --diff ec_tools
      - name: isort
        shell: bash -l {0}
        run: |
          isort --check --diff ec_tools
